--Top 3 Usuários com Maior Número de Sessões de Treino no Mês Atual:
SELECT
    U.NOME,
    COUNT(E.EXERCICIO_ID) AS NUMERO_SESSOES
FROM
    USUARIO U
JOIN
    EXERCICIO E ON U.USUARIO_ID = E.USER_ID
WHERE
    EXTRACT(MONTH FROM E.DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
GROUP BY
    U.USUARIO_ID, U.NOME, U.SOBRENOME
ORDER BY
    NUMERO_SESSOES DESC
LIMIT 3;

-- Top 3 Usuários com Maior Peso Utilizado no Mês Atual:
SELECT
    U.NOME,
    E.NOME AS NOME_EXERCICIO,
    MAX(E.WEIGHT_USED) AS MAIOR_PESO_UTILIZADO
FROM
    USUARIO U
JOIN
    EXERCICIO E ON U.USUARIO_ID = E.USER_ID
WHERE
    EXTRACT(MONTH FROM E.DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
GROUP BY
    U.USUARIO_ID, U.NOME, U.SOBRENOME
ORDER BY
    MAIOR_PESO_UTILIZADO DESC
LIMIT 3;



--Top 3 usuarios com maior quantidades de horas registradas
SELECT
    U.NOME,
    SUM(E.DURATION) AS TEMPO_TOTAL_EXERCICIOS
FROM
    USUARIO U
JOIN
    EXERCICIO E ON U.USUARIO_ID = E.USER_ID
WHERE
    EXTRACT(MONTH FROM E.DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
GROUP BY
    U.USUARIO_ID, U.NOME, U.SOBRENOME
ORDER BY
    TEMPO_TOTAL_EXERCICIOS DESC
LIMIT 3;
