CREATE TABLE USUARIO(
	USUARIO_ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100),
	SOBRENOME VARCHAR(100),
	DATA_NASCIMENTO DATE NOT NULL,
	PESO FLOAT NOT NULL,
	ALTURA FLOAT NOT NULL
);

CREATE TABLE LOGIN(
	LOGIN_ID SERIAL PRIMARY KEY,
	USUARIO VARCHAR(100) NOT NULL UNIQUE,
	SENHA VARCHAR(100) NOT NULL
);

CREATE TABLE EXERCICIO(
	EXERCICIO_ID SERIAL PRIMARY KEY,
	NOME VARCHAR(100)  NOT NULL,
	GRUPO_MUSCULAR VARCHAR(50) NOT NULL,
	PARTE_MUSCULAR VARCHAR(50) NOT NULL,
	EQUIPAMENTO VARCHAR(100) NULL,
	PESO_UTILIZADO FLOAT NOT NULL,
	DATA DATE NOT NULL,
	HORA TIME NOT NULL,
	REPETICOES INT NOT NULL
);

ALTER TABLE LOGIN
ADD COLUMN USUARIO_ID INT,
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (USUARIO_ID) 
REFERENCES USUARIO(USUARIO_ID);

ALTER TABLE EXERCICIO
ADD COLUMN USUARIO_ID INT,
ADD CONSTRAINT FK_USUARIO
FOREIGN KEY (USUARIO_ID) 
REFERENCES USUARIO(USUARIO_ID);
