CREATE TABLE USER_(
	USER_ID SERIAL PRIMARY KEY,
	FIST_NAME VARCHAR(100),
	LAST_NAME VARCHAR(100),
	DATE_BIRTH DATE NOT NULL,
	WEIGHT FLOAT NOT NULL,
	HEIGTH FLOAT NOT NULL
);

CREATE TABLE LOGIN(
	LOGIN_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE EXERCISE(
	EXERCISE_ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100)  NOT NULL,
	MUSCLE_GROUP VARCHAR(50) NOT NULL,
	MUSCLE_PART VARCHAR(50) NOT NULL,
	EQUIPMENT VARCHAR(100) NULL,
	WEIGHT_USED FLOAT NOT NULL,
	DATE DATE NOT NULL,
	HOUR TIME NOT NULL,
	REPETITIONS INT NOT NULL
);

ALTER TABLE LOGIN
ADD COLUMN USER_ID INT,
ADD CONSTRAINT FK_USER_
FOREIGN KEY (USER_ID) 
REFERENCES user_(USER_ID);

ALTER TABLE EXERCISE
ADD COLUMN USER_ID INT,
ADD CONSTRAINT FK_USER_
FOREIGN KEY (USER_ID) 
REFERENCES user_(USER_ID);


